package uk.co.oliverdelange.wcr_android_kt.db.dao.local

import androidx.annotation.WorkerThread
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import io.reactivex.Completable
import io.reactivex.Maybe
import uk.co.oliverdelange.wcr_android_kt.db.dto.local.BaseEntity

/*
* https://developer.android.com/training/data-storage/room/accessing-data#convenience-insert
* Insert can only return row-id from autogenerated primary key
* */
@WorkerThread
interface BaseDao<T : BaseEntity> {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun insert(obj: T)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun insertMany(vararg objs: T)

    fun loadYetToBeUploaded(): Maybe<List<T>>

    fun updateUploadedAt(id: String, uploadedAt: Long): Completable

//    fun updateFirebaseId(id: Long, firebaseId: String): Completable
}